#!/bin/bash

SERVICE_NAME=Hdfs-Over-Ftp
PATH_TO_JARS=/home/hdfsoverftp/hdfs-over-ftp/hdfs-over-ftp-1.1-SNAPSHOT.jar:.
MAIN_CLASS=org.apache.hadoop.contrib.ftp.HdfsOverFtpServer
PID_PATH_NAME=/home/hdfsoverftp/hdfs-over-ftp/hdfs-over-ftp.pid
LOG_FILE=hdfs-over-ftp_start.log

case $1 in
    start)
        echo "Starting $SERVICE_NAME ..."
        if [ ! -f $PID_PATH_NAME ]; then
            nohup java -cp $PATH_TO_JARS $MAIN_CLASS &> $LOG_FILE &
            echo $! > $PID_PATH_NAME
            echo "$SERVICE_NAME started ..."
        else
            echo "$SERVICE_NAME is already running ..."
        fi
    ;;
    stop)
        if [ -f $PID_PATH_NAME ]; then
            PID=$(cat $PID_PATH_NAME);
            echo "$SERVICE_NAME stoping ..."
            kill $PID;
            echo "$SERVICE_NAME stopped ..."
            rm $PID_PATH_NAME
        else
            echo "$SERVICE_NAME is not running ..."
        fi
    ;;
    restart)
        if [ -f $PID_PATH_NAME ]; then
            PID=$(cat $PID_PATH_NAME);
            echo "$SERVICE_NAME stopping ...";
            kill $PID;
            echo "$SERVICE_NAME stopped ...";
            rm $PID_PATH_NAME
            echo "$SERVICE_NAME starting ..."
            nohup java -cp $PATH_TO_JARS $MAIN_CLASS &> $LOG_FILE &
            echo $! > $PID_PATH_NAME
            echo "$SERVICE_NAME started ..."
        else
            echo "$SERVICE_NAME is not running ..."
        fi
    ;;
esac 
